### ISSUE TITLE
csc: file `' does not exist / csc: file `mpi.import.scm' does not exist.

### ISSUE THREAD

**Issue by ivan-avalos** [iraikov/chicken-mpi#1] opened 2020-06-11 01:36 UTC
I already have `open-mpi` installed on my system under `/usr/local/lib` and `/usr/local/include`, but when I try to install the egg (even if I set the LDFLAGS `
LDFLAGS="-L/usr/local/lib/openmpi -I/usr/local/include/openmpi" sudo chicken-install mpi
`), I keep getting the following error:
```
building mpi
   /Users/avalos/.cache/chicken-install/mpi/build.sh -host -D compiling-extension -J -s -regenerate-import-libraries -setup-mode -I /Users/avalos/.cache/chicken-install/mpi -C -I/Users/avalos/.cache/chicken-install/mpi -O2 -d1 mpi.scm -o /Users/avalos/.cache/chicken-install/mpi/mpi.so
header: #include <mpi.h> cppflags:  ldflags: -lmpi
clang   -fno-strict-aliasing -fwrapv -fno-common -DHAVE_CHICKEN_CONFIG_H -m64 -DC_ENABLE_PTABLES -Os -fomit-frame-pointer '/tmp/temp529b.96250.c' -o '/tmp/temp529b.96250.o' -L/usr/local/Cellar/chicken/5.2.0/lib -lmpi -lm ...
succeeded.
csc: file `' does not exist
   /Users/avalos/.cache/chicken-install/mpi/build.sh -regenerate-import-libraries -M -setup-mode -static -I /Users/avalos/.cache/chicken-install/mpi -emit-link-file /Users/avalos/.cache/chicken-install/mpi/mpi.link -host -D compiling-extension -c -unit mpi -D compiling-static-extension -C -I/Users/avalos/.cache/chicken-install/mpi -O2 -d1 mpi.scm -o /Users/avalos/.cache/chicken-install/mpi/mpi.static.o
header: #include <mpi.h> cppflags:  ldflags: -lmpi
clang   -fno-strict-aliasing -fwrapv -fno-common -DHAVE_CHICKEN_CONFIG_H -m64 -DC_ENABLE_PTABLES -Os -fomit-frame-pointer '/tmp/temp529b.96260.c' -o '/tmp/temp529b.96260.o' -L/usr/local/Cellar/chicken/5.2.0/lib -lmpi -lm ...
succeeded.
csc: file `' does not exist
   /usr/local/Cellar/chicken/5.2.0/bin/csc -setup-mode -s -host -I /Users/avalos/.cache/chicken-install/mpi -C -I/Users/avalos/.cache/chicken-install/mpi -O2 -d0 mpi.import.scm -o /Users/avalos/.cache/chicken-install/mpi/mpi.import.so
csc: file `mpi.import.scm' does not exist

Error: shell command terminated with nonzero exit code
16384
"sh /Users/avalos/.cache/chicken-install/mpi/mpi.build.sh"
```

I built `open-mpi` from sources, following the normal instructions. I'm using macOS 10.15.4, btw.

```
./configure
make all
sudo make install
```

**Comment by iraikov** [comment] 2020-06-11 14:41
Hi Ivan,
Thanks for the bug report. I don't have access to a MacOS system, but should be able to set up a CI MacOS environment via GitHub Actions. I believe their MacOS image uses Homebrew, which in turn has an OpenMPI package. Let me set this up first.

**Comment by ivan-avalos** [comment] 2020-06-11 16:22
I also tried with Linux Alpine via Docker, with the following Dockerfile:
```
FROM alpine:edge
WORKDIR /app
RUN apk add chicken zsh
RUN apk --no-cache add openmpi openmpi-dev \
    --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
RUN chicken-install srfi-1 list-utils gochan mpi
COPY ./ ./
CMD ["csi", "regu.scm"]
```

The output is:
```
   /usr/bin/csc -host -D compiling-extension -J -s -regenerate-import-libraries -setup-mode -I /root/.cache/chicken-install/compile-file -C -I/root/.cache/chicken-install/compile-file -O2 -d1 compile-file.scm -o /root/.cache/chicken-install/compile-file/compile-file.so
   /usr/bin/csc -regenerate-import-libraries -M -setup-mode -static -I /root/.cache/chicken-install/compile-file -emit-link-file /root/.cache/chicken-install/compile-file/compile-file.link -host -D compiling-extension -c -unit compile-file -D compiling-static-extension -C -I/root/.cache/chicken-install/compile-file -O2 -d1 compile-file.scm -o /root/.cache/chicken-install/compile-file/compile-file.static.o
   /usr/bin/csc -setup-mode -s -host -I /root/.cache/chicken-install/compile-file -C -I/root/.cache/chicken-install/compile-file -O2 -d0 compile-file.import.scm -o /root/.cache/chicken-install/compile-file/compile-file.import.so
  installing compile-file
building mpi
   /root/.cache/chicken-install/mpi/build.sh -host -D compiling-extension -J -s -regenerate-import-libraries -setup-mode -I /root/.cache/chicken-install/mpi -C -I/root/.cache/chicken-install/mpi -O2 -d1 mpi.scm -o /root/.cache/chicken-install/mpi/mpi.so
executing command failed: Exec format error

Error: shell command terminated with nonzero exit code
256
"sh /root/.cache/chicken-install/mpi/mpi.build.sh"
The command '/bin/sh -c chicken-install srfi-1 list-utils gochan mpi' returned a non-zero code: 70
```

**Comment by iraikov** [comment] 2020-06-11 19:08
The Github CI action worked with their Ubuntu image, but the MacOS one failed with the same error as in your report, so at least the error is reproducible. I will look at this again later today to see if I can fix it.

**Comment by ivan-avalos** [comment] 2020-06-11 20:04
Thanks! I think it is related with the location of the libraries. Is it possible to specify a non-standard prefix? Homebrew installs to `/usr/local/Cellar`, for example.

**Comment by iraikov** [comment] 2020-06-15 17:06
Hi Ivan,
I believe building on Mac OS X is now fixed. The CI test still fails because mpirun thinks there are not enough CPU slots available for 8 MPI processes (but the same test works on the Linux image). I will see if I can fix that, but meanwhile you can check if the master branch works on your system.

**Comment by ivan-avalos** [comment] 2020-06-15 18:35
Awesome! I will try it and let you know if it works! Thanks!

**Comment by ivan-avalos** [comment] 2020-06-16 19:01
I could already install the module! Thanks so much!

**Closed as completed** 2020-06-16 19:01 UTC
